# Generated by Django 6.0.2 on 2026-02-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailverification_id_alter_profile_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
