# Generated by Django 6.0.2 on 2026-03-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0004_delete_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_products',
            field=models.ManyToManyField(blank=True, related_name='assigned_students', to='products.uniform'),
        ),
    ]
