# Generated by Django 4.2.30 on 2026-10-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_assigned_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_year',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Program & Year Level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Administrator'), ('staff', 'Staff / Faculty')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Student / ID Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Complete Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number'),
        ),
    ]
