# Generated by Django 6.0.2 on 2026-04-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_product_id_remove_order_quantity_and_more'),
    ]

    operations = [
    ]
