# Generated by Django 6.0.2 on 2026-04-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20260405_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Order Arrived'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
