# Generated by Django 6.0.2 on 2026-04-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniform',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uniform',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='uniform',
            name='size',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='UniformSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('ONE_SIZE', 'One Size Fits All')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.uniform')),
            ],
            options={
                'ordering': ['size'],
                'unique_together': {('uniform', 'size')},
            },
        ),
    ]
