# Generated by Django 4.2.30 on 2026-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_uniform_image_url_alter_uniform_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniform',
            name='category',
            field=models.CharField(blank=True, choices=[('uniforms', 'Campus Uniforms'), ('department', 'Department Polos'), ('bottoms', 'Slacks & Pants'), ('lanyards', 'Lanyards & IDs')], default='', max_length=20),
        ),
    ]
