# Generated by Django 4.2.30 on 2026-10-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_uniform_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='category',
            field=models.CharField(blank=True, choices=[('uniforms', 'Campus Uniforms'), ('department', 'Department Uniforms'), ('organization', 'Organization Uniforms'), ('bottoms', 'Slacks & Pants'), ('lanyards', 'Lanyards & IDs')], default='', max_length=20),
        ),
    ]
